
INCLUDE(CheckCXXSourceCompiles)

SET(gtest_default "

#include <gtest/gtest.h>

TEST(gtest_test, defualt)
{
    EXPECT_EQ(0, 1);
}

"
)

CHECK_CXX_SOURCE_COMPILES("${gtest_default}" GTEST_SUCCESS)

IF(NOT GTEST_SUCCESS)
    # Try with thread library
    FIND_PACKAGE(Threads)
    SET(CMAKE_REQUIRED_LIBRARIES ${CMAKE_THREAD_LIBS_INIT})
    CHECK_CXX_SOURCE_COMPILES("${gtest_default}" GTEST_SUCCESS)
    SET(GTEST_THREAD_LIBRARIES ${CMAKE_THREAD_LIBS_INIT})
ENDIF()


IF(APPLE)
    EXEC_PROGRAM(uname ARGS -v  OUTPUT_VARIABLE DARWIN_VERSION)
    STRING(REGEX MATCH "[0-9]+" DARWIN_VERSION ${DARWIN_VERSION})
    #MESSAGE(STATUS "DARWIN_VERSION=${DARWIN_VERSION}")
    #DARWIN version 13 = Mac 0SX 10.9
    IF(DARWIN_VERSION GREATER 12)
        ADD_DEFINITIONS(-DGTEST_USE_OWN_TR1_TUPLE=1)
    ENDIF ()
ENDIF()



