
# Defines APIPP_SRCS
SET( APIPP_HDRS
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/context.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/differentialoperator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/element.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldcache.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/field.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldmodule.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesalias.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesarithmeticoperators.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypescomposite.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesconditional.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesconstant.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypescoordinatetransformation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesderivatives.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesfiniteelement.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesgroup.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesimage.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesimageprocessing.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypeslogicaloperators.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesmatrixoperators.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesnodesetoperators.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypessubobjectgroup.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypestime.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypestrigonometry.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/fieldtypesvectoroperators.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/glyph.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/graphic.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/graphicsfilter.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/font.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/graphicsmaterial.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/graphicsmodule.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/optimisation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/region.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/rendition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/scene.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/scenepicker.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/sceneviewer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/selection.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/spectrum.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/stream.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/tessellation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/timenotifier.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/timekeeper.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/source/api/zinc/timesequence.hpp
    )
