
# Defines APIPP_SRCS
SET( APIPP_HDRS
    source/api++/context.hpp
    source/api++/differentialoperator.hpp
    source/api++/element.hpp
    source/api++/fieldcache.hpp
    source/api++/field.hpp
    source/api++/fieldmodule.hpp
    source/api++/fieldtypesarithmeticoperators.hpp
    source/api++/fieldtypescomposite.hpp
    source/api++/fieldtypesconditional.hpp
    source/api++/fieldtypesconstant.hpp
    source/api++/fieldtypescoordinatetransformation.hpp
    source/api++/fieldtypesfiniteelement.hpp
    source/api++/fieldtypesgroup.hpp
    source/api++/fieldtypesimage.hpp
    source/api++/fieldtypeslogicaloperators.hpp
    source/api++/fieldtypesmatrixoperators.hpp
    source/api++/fieldtypesnodesetoperators.hpp
    source/api++/fieldtypessubobjectgroup.hpp
    source/api++/fieldtypestime.hpp
    source/api++/fieldtypestrigonometry.hpp
    source/api++/fieldtypesvectoroperators.hpp
    source/api++/graphic.hpp
    source/api++/graphicsfilter.hpp
    source/api++/graphicsmaterial.hpp
    source/api++/graphicsmodule.hpp
    source/api++/node.hpp
    source/api++/optimisation.hpp
    source/api++/region.hpp
    source/api++/rendition.hpp
    source/api++/scene.hpp
    source/api++/sceneviewer.hpp
    source/api++/selection.hpp
    source/api++/spectrum.hpp
    source/api++/stream.hpp
    source/api++/tessellation.hpp
    source/api++/time.hpp
    source/api++/timekeeper.hpp
    source/api++/timesequence.hpp
    )
