#if ! defined (PERL_CMISS_VARIABLE_NEW_COMPOSITION_TYPEMAP_H)
#define PERL_CMISS_VARIABLE_NEW_COMPOSITION_TYPEMAP_H

#include "perl/Cmiss/Variable_new/typemap.h"

#endif /* ! defined (PERL_CMISS_VARIABLE_NEW_COMPOSITION_TYPEMAP_H) */
