#if ! defined (PERL_CMISS_VARIABLE_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H)
#define PERL_CMISS_VARIABLE_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H

#include "perl/Cmiss/Variable/typemap.h"

#endif /* ! defined (PERL_CMISS_VARIABLE_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H) */
