/**
 * FILE : scenecoordinatesystem.hpp
 *
 * Enumerated type for identifying scene and window coordinate systems.
 */
/* OpenCMISS-Zinc Library
*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef CMZN_SCENECOORDINATESYSTEM_HPP__
#define CMZN_SCENECOORDINATESYSTEM_HPP__

#include "scenecoordinatesystem.h"

namespace OpenCMISS
{
namespace Zinc
{

/**
 * Enumerated type for identifying scene and window coordinate systems.
 */
enum SceneCoordinateSystem
{
	SCENE_COORDINATE_SYSTEM_INVALID = CMZN_SCENE_COORDINATE_SYSTEM_INVALID,
	SCENE_COORDINATE_SYSTEM_LOCAL = CMZN_SCENE_COORDINATE_SYSTEM_LOCAL,
	SCENE_COORDINATE_SYSTEM_WORLD = CMZN_SCENE_COORDINATE_SYSTEM_WORLD,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FILL = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FILL,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_CENTRE = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_CENTRE,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_LEFT = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_LEFT,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_RIGHT = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_RIGHT,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_BOTTOM = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_BOTTOM,
	SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_TOP = CMZN_SCENE_COORDINATE_SYSTEM_NORMALISED_WINDOW_FIT_TOP,
	SCENE_COORDINATE_SYSTEM_WINDOW_PIXEL_BOTTOM_LEFT = CMZN_SCENE_COORDINATE_SYSTEM_WINDOW_PIXEL_BOTTOM_LEFT,
	SCENE_COORDINATE_SYSTEM_WINDOW_PIXEL_TOP_LEFT = CMZN_SCENE_COORDINATE_SYSTEM_WINDOW_PIXEL_TOP_LEFT
};

} // namespace Zinc
}

#endif
