#if ! defined (PERL_CMISS_VARIABLE_NEW_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H)
#define PERL_CMISS_VARIABLE_NEW_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H

#include "perl/Cmiss/Variable_new/typemap.h"
typedef Cmiss_variable_new_id Cmiss__Variable_new__Prolate_spheroidal_to_rectangular_cartesian;

#endif /* ! defined (PERL_CMISS_VARIABLE_NEW_PROLATE_SPHEROIDAL_TO_RECTANGULAR_CARTESIAN_TYPEMAP_H) */
