#if ! defined (PERL_CMISS_VARIABLE_SPHEROIDAL_COORDINATES_FOCUS_TYPEMAP_H)
#define PERL_CMISS_VARIABLE_SPHEROIDAL_COORDINATES_FOCUS_TYPEMAP_H

#include "perl/Cmiss/Variable/typemap.h"

#endif /* ! defined (PERL_CMISS_VARIABLE_SPHEROIDAL_COORDINATES_FOCUS_TYPEMAP_H) */
