
from distutils.core import setup, Extension

setup(name="Cmiss",
      version="1.0",
      description="Cmiss python interface",
      author="Shane Blackett",
      author_email="s.blackett@auckland.ac.nz",
      url="http://www.cmiss.org",
      packages=['Cmiss', 'Cmiss.Region', 'Cmiss.Value', 'Cmiss.Variable'],
      ext_modules=[
        Extension("Cmiss.Cmgui_command_data", ["Cmiss/Cmgui_command_data.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui"]),
        Extension("Cmiss.FE_field", ["Cmiss/FE_field.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
        Extension("Cmiss.FE_element", ["Cmiss/FE_element.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_finite_element"]),
        Extension("Cmiss.FE_node", ["Cmiss/FE_node.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_finite_element"]),
         Extension("Cmiss.Interpreter", ["Cmiss/Interpreter.c"],
          include_dirs=["/usr/people/blackett/perl_interpreter/source"],
          define_macros=[('FULL_NAMES', '1')]),
        Extension("Cmiss.Region.Region", ["Cmiss/Region/Region.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_finite_element"]),
        Extension("Cmiss.Value.Value", ["Cmiss/Value/Value.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
        Extension("Cmiss.Value.Matrix", ["Cmiss/Value/Matrix.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
         Extension("Cmiss.Value.Derivative_matrix", ["Cmiss/Value/Derivative_matrix.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
         Extension("Cmiss.Value.Element_xi", ["Cmiss/Value/Element_xi.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
         Extension("Cmiss.Value.FE_value_vector", ["Cmiss/Value/FE_value_vector.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
        Extension("Cmiss.Variable.Variable", ["Cmiss/Variable/Variable.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
        Extension("Cmiss.Variable.Derivative", ["Cmiss/Variable/Derivative.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable"]),
        Extension("Cmiss.Variable.Element_xi", ["Cmiss/Variable/Element_xi.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable_finite_element"]),
        Extension("Cmiss.Variable.Finite_element", ["Cmiss/Variable/Finite_element.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui_computed_variable_finite_element"]),
        Extension("Cmiss.Variable.Nodal_value", ["Cmiss/Variable/Nodal_value.c"],
          include_dirs=["/usr/people/blackett/cmgui/source"],
          define_macros=[('FULL_NAMES', '1')],
          library_dirs=["/home/blackett/lib"],
          libraries=["cmgui"])]
     )

