/* OpenCMISS-Zinc Library
*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#if !defined CMZN_LICENSE_STRING
#include <string>
const char *CMZN_LICENSE_STRING ={
"OpenCMISS-Zinc Library\n"
"\n"
"This Source Code Form is subject to the terms of the Mozilla Public\n"
"License, v. 2.0. If a copy of the MPL was not distributed with this\n"
"file, You can obtain one at http://mozilla.org/MPL/2.0/.\n"
"\n"
"Cmgui is developed and built with the following sources.\n"
"\n"
"ImageMagick-5.3.3\n"
"Copyright (C) 2000 ImageMagick Studio\nhttp://www.imagemagick.org\n"
"\n"
"Tiff\n"
"Copyright (c) 1988-1997 Sam Leffler\n"
"Copyright (c) 1991-1997 Silicon Graphics, Inc.\nhttp://www.libtiff.org\n"
"\n"
"JPEG\n"
"This software is copyright (C) 1991-1998, Thomas G. Lane.\nhttp://www.ijg.org\n"
"\n"
"zlib\n"
"Copyright (c) 1995-1998 Jean-loup Gailly and Mark Adler\n"
"ftp://ftp.uu.net/pub/archiving/zip/zlib/zlib-1.1.3,gz\n"
"\n"
"pnglib\n"
"Copyright (c) 2000 Glenn Randers-Pehrso\n"
"\n"
"libxml2\n"
"Copyright (C) 1998-2002 Daniel Veillard.\n"
"\n"
"wxWidgets\n"
"Copyright (C) 1998-2009 Julian Smart, Robert Roebling et al\n"
"http://wxwidgets.org/\n"
"\n"
"ITK\n"
"Copyright (c) 1999-2003 Insight Software Consortium\n"
"\n"
"GDCM\n"
"Copyright (c) 2006-2009 Mathieu Malaterre\n"
"Copyright (c) 1993-2005 CREATIS\n"
"\n"
"Netgen\n"
"By Joachim Schoberl\n"
"\n"
"OpenGL Extension Wrangler Library\n"
"The OpenGL Extension Wrangler Library\n"
"Copyright (C) 2002-2008, Milan Ikits <milan ikits[]ieee org>\n"
"Copyright (C) 2002-2008, Marcelo E. Magallon <mmagallo[]debian org>\n"
"Copyright (C) 2002, Lev Povalahev\n"
"All rights reserved.\n"
"\n"
"FreeType 2.4.10\n"
"Copyright 2006-2011 by\n"
"David Turner, Robert Wilhelm, and Werner Lemberg.\n"
"\n"
"FTGL\n"
"Copyright (C) 2001-3 Henry Maddocks\n"
"\n"
"OPT++ Class Libraries License Version 2.0, November 2001\n"
"Copyright (2001) Sandia Corporation.\n"
};
#endif /* CMZN_LICENSE_STRING */
