
IF( ZINC_USE_STATIC )
    SET(ZINC_LIBRARY @ZINC_STATIC_TARGET@ CACHE STRING "The static Zinc library target" )
    ADD_DEFINITIONS( @ZINC_STATIC_DEFINITIONS@ )
ELSE()
    SET(ZINC_LIBRARY @ZINC_SHARED_TARGET@ CACHE STRING "The shared Zinc library target" )
    ADD_DEFINITIONS( @ZINC_SHARED_DEFINITIONS@ )
ENDIF()

