
SET(ZINC_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
IF(WIN32)
	STRING(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} ZINC_ARCHITECTURE)
ENDIF()

SET(CPACK_PACKAGE_VERSION_MAJOR "1")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")

FUNCTION( GET_ZINC_SYSTEM_NAME RETURN_SYSTEM_NAME )
	IF( WIN32 )
		SET( SYSTEM_NAME "Windows" )
	ELSEIF( APPLE )
		EXECUTE_PROCESS(COMMAND sw_vers -productName RESULT_VARIABLE COMMAND_RESULT OUTPUT_VARIABLE PRODUCT_NAME )
		STRING( STRIP ${PRODUCT_NAME} PRODUCT_NAME )
		EXECUTE_PROCESS(COMMAND sw_vers -productVersion RESULT_VARIABLE COMMAND_RESULT OUTPUT_VARIABLE PRODUCT_VERSION )
		STRING( STRIP ${PRODUCT_VERSION} PRODUCT_VERSION )
		STRING( REPLACE " " "-" SYSTEM_NAME "${PRODUCT_NAME} ${PRODUCT_VERSION}" )
	ELSEIF( UNIX )
		SET( SYSTEM_NAME "Linux" )
		EXECUTE_PROCESS(COMMAND cat /etc/issue RESULT_VARIABLE COMMAND_RESULT OUTPUT_VARIABLE COMMAND_OUTPUT ERROR_VARIABLE ERROR_OUTPUT)
		IF( COMMAND_RESULT EQUAL 0 )
			STRING( REGEX MATCH "^[^\\]*" COMMAND_OUTPUT ${COMMAND_OUTPUT} )
			STRING( STRIP ${COMMAND_OUTPUT} COMMAND_OUTPUT )
			STRING( REPLACE " " "-" SYSTEM_NAME ${COMMAND_OUTPUT} )
		ENDIF()
	ELSE()
		MESSAGE( FATAL_ERROR "Don't yet know this system." )
	ENDIF()

	SET( ${RETURN_SYSTEM_NAME} ${SYSTEM_NAME} PARENT_SCOPE)
ENDFUNCTION()

GET_ZINC_SYSTEM_NAME( ZINC_SYSTEM )

IF( WIN32 )
	MESSAGE( STATUS "Please implement NSIS installer for me." )
	SET( CPACK_GENERATOR "ZIP" )
ELSEIF( APPLE )
	# Preserve the CMAKE_INSTALL_PREFIX for the project and work with absolute install
	SET(CPACK_SET_DESTDIR ON)

	SET( CPACK_RESOURCE_FILE_WELCOME "${CMAKE_CURRENT_SOURCE_DIR}/distrib/osx/welcome.txt" )
	LIST( LENGTH LENGTH_ARCHS CMAKE_OSX_ARCHITECTURES )
	message(STATUS "la=${LENGTH_ARCHS}-${CMAKE_OSX_ARCHITECTURES}")
	message(STATUS "la=${CMAKE_SYSTEM_NAME}-${CMAKE_OSX_ARCHITECTURES}")

	SET( ZINC_ARCHITECTURE "universal" )
	SET( CPACK_GENERATOR  "TGZ" "PackageMaker" )
ELSEIF( UNIX )
	# Preserve the CMAKE_INSTALL_PREFIX for the project and work with absolute install
	SET(CPACK_SET_DESTDIR ON)

	SET( CPACK_GENERATOR "TGZ" )
	STRING( FIND ${ZINC_SYSTEM} "Ubuntu" INDEX )
	IF( INDEX EQUAL 0 )
		SET( CPACK_DEBIAN_PACKAGE_MAINTAINER "Hugh Sorby" ) #required
		LIST( APPEND CPACK_GENERATOR "DEB" )
	ENDIF()
ENDIF()

SET( CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt" )
SET( CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.txt" )
SET( CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/distrib/description.txt" )
SET( CPACK_PACKAGE_VENDOR "physiomeproject" )

SET( CPACK_PACKAGE_FILE_NAME "zinc-${ZINC_VERSION}-${ZINC_ARCHITECTURE}-${ZINC_SYSTEM}" )
SET( CPACK_OUTPUT_FILE_PREFIX "package" )

INCLUDE(CPack)

