
SET(ZINC_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR})
IF(CMAKE_CL_64)
    SET(ZINC_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR}_64)
ENDIF()

# Preserve the CMAKE_INSTALL_PREFIX for the project and work with absolute install
SET(CPACK_SET_DESTDIR ON)

SET(CPACK_PACKAGE_VERSION_MAJOR "${ZINC_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${ZINC_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${ZINC_PATCH_VERSION}")

SET( CPACK_GENERATOR "TGZ;DEB" )
SET( CPACK_DEBIAN_PACKAGE_MAINTAINER "Hugh Sorby" ) #required
SET( CPACK_PACKAGE_FILE_NAME "zinc-${ZINC_VERSION}-${ZINC_ARCHITECTURE}-${CMAKE_SYSTEM}" )

INCLUDE(CPack)
