
# Defines CMGUI_LIB_SRCS
SET( CMGUI_LIB_BASE_SRCS ${API_SRCS} ${COMFILE_SRCS} ${COMMAND_SRCS}
	${COMPUTED_FIELD_SRCS} ${CONTEXT_SRCS} ${CURVE_SRCS} ${ELEMENT_SRCS} ${EMOTER_SRCS}
	${FINITE_ELEMENT_GRAPHICS_SRCS} ${FINITE_ELEMENT_ADDITIONAL_SRCS} ${GENERAL_SRCS}
	${GRAPHICS_SRCS} ${HELP_SRCS} ${IMAGE_PROCESSING_SRCS} ${INTERACTION_SRCS}
	${IO_DEVICES_SRCS} ${NODE_SRCS} ${SELECTION_SRCS} ${INTERPRETER_SRCS} 
	${THREE_D_DRAWING_SRCS} ${TIME_SRCS} ${USER_INTERFACE_SRCS} )

IF( WX_USER_INTERFACE )
	SET( CMGUI_LIB_INTERFACE_SRCS ${API_INTERFACE_SRCS} ${COLOUR_INTERFACE_SRCS}
		${COMFILE_INTERFACE_SRCS}
		${COMMAND_INTERFACE_SRCS} ${COMPUTED_FIELD_INTERFACE_SRCS}
		${GRAPHICS_INTERFACE_SRCS}
		${MATERIAL_INTERFACE_SRCS} ${NODE_INTERFACE_SRCS}
		${REGION_INTERFACE_SRCS}
		${TRANSFORMATION_INTERFACE_SRCS} )
ENDIF( WX_USER_INTERFACE )

SET( CMGUI_LIB_SRCS
	${CMGUI_LIB_BASE_SRCS}
	${CMGUI_LIB_INTERFACE_SRCS} )

SET( CMGUI_LIB_HDRS
	${wxWidgets_GENERATED_HDRS} )
#	source/api/cmiss_command_data.c
#	source/api/cmiss_field.c
#	source/api/cmiss_region.c )

#IF( ${GRAPHICS_API} MATCHES OPENGL_GRAPHICS )
#	SET( CMGUI_LIB_SRCS ${CMGUI_LIB_SRCS}
#		source/api/cmiss_scene_viewer.cpp
#		source/api/cmiss_texture.c )
#ENDIF( ${GRAPHICS_API} MATCHES OPENGL_GRAPHICS )
 
