/* @(#)99	1.1  com/config/uilmain.tem, aic, aic324, 9317324 4/2/93 17:34:29 */
/*
 *  COMPONENT_NAME: AIC           AIXwindows Interface Composer
 *  
 *  ORIGINS: 58
 *  
 *  
 *                   Copyright IBM Corporation 1991, 1993
 *  
 *                         All Rights Reserved
 *  
 *   Permission to use, copy, modify, and distribute this software and its
 *   documentation for any purpose and without fee is hereby granted,
 *   provided that the above copyright notice appear in all copies and that
 *   both that copyright notice and this permission notice appear in
 *   supporting documentation, and that the name of IBM not be
 *   used in advertising or publicity pertaining to distribution of the
 *   software without specific, written prior permission.
 *  
*/
/*-----------------------------------------------------------
 * This is the project main program file for Xt generated 
 * code. You may add application dependent source code 
 * at the appropriate places. 
 * 			     
 * Do not modify the statements preceded by the dollar
 * sign ($), these statements will be replaced with
 * the appropriate source code when the main program is  
 * generated.  
 *
 * $Date$  		$Revision$ 
 *-----------------------------------------------------------*/ 

/*-----------------------------------------------------------
 *
 *             Copyright (c) 1992, Visual Edge Software Ltd.
 *
 * ALL  RIGHTS  RESERVED.  Permission  to  use,  copy,  modify,  and
 * distribute  this  software  and its documentation for any purpose
 * and  without  fee  is  hereby  granted,  provided  that the above
 * copyright  notice  appear  in  all  copies  and  that  both  that
 * copyright  notice and this permission notice appear in supporting
 * documentation,  and that  the name of Visual Edge Software not be
 * used  in advertising  or publicity  pertaining to distribution of
 * the software without specific, written prior permission. The year
 * included in the notice is the year of the creation of the work.
 *-------------------------------------------------------------------*/
/* ---------------------------------------------------------------------------
FUNCTION:	main()

Use this file for making an application executable containing C code
generated by Architect (UIL Code option).

This file provides a typical main function to link with C code generated
by Architect.  The object code derived from this file would be linked with
the object code from the C files generated by Architect and the application
object code to produce a standalone application executable.

Normally, there will be one main interface which appears at initialization
time.  In the C code for that interface, an interface function is defined; this
is the last function in the C file and will be of the form create_<widgetname>()
or popup_<widgetname>.  This function should be called after XtAppInitialize()
in order to display the initial interface.  In the examples below,
the function create_$PJ_IFACE_NAME() has been used; you should replace 
this with the appropriate interface function from your generated C code file.

In the following code, we assume that a create_ function has been
written to the generated C code.  This function merely creates the
interface, but does not make it visible.  Thus it is necessary to call
UxPopupInterface() to pop up the interface.  Alternatively, the developer
can request Architect to write a popup_ function to the generated C code
by setting the InterfaceFunctionType resource in the Options menu.
The popup_ function creates the interface, and then calls UxPopupInterface()
to pop it up.  The popup_ function is thus useful since one function call
both creates the interface and pops it up; the create_ function is useful
when the user wants to initialize all interfaces first, and then pop them
up as needed.  Both the popup_ and create_ functions return the toplevel widget
in the interface, which can be used as an argument to UxPopupInterface(),
UxPopdownInterface() and UxDestroyInterface().

For the implicit event loop version, after popping up the initial
interface XtAppMainLoop() is called.  This function never returns since the
interface handles all subsequent events.  In the explicit event loop version
XtAppMainLoop has been replaced with a for loop and the XtNexEvent() and
XtDispatchEvent() functions.  Simply add 'case' statements with code to handle
the events you do not want the interface to handle.

------------------------------------------------------------------------------*/

#include <stdio.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <Xm/Xm.h>
#include <Mrm/MrmPublic.h>

/*---------------------------------------------------- 
 * UxXt.h needs to be included only when compiling a 
 * stand-alone application. 
 *---------------------------------------------------*/
#ifndef DESIGN_TIME
#include "UxXt.h"
#endif /* DESIGN_TIME */
#include "XvgGlobals.h"

XtAppContext	UxAppContext;
Widget		UxTopLevel;
Display		*UxDisplay;
int		UxScreen;

static int argc_xvg;
static char **argv_xvg;

/*----------------------------------------------
 * Insert application global declarations here
 *---------------------------------------------*/

#if (!defined (CMGUI) || !defined (NO_XVGMAIN))
void XvgInitX(void)
{
#ifdef XOPEN_CATALOG
  XtSetLanguageProc(NULL,(XtLanguageProc)NULL,NULL);
#endif
  MrmInitialize();
  
  UxTopLevel = XtAppInitialize(&UxAppContext, "xvg",
			       NULL, 0, &argc_xvg, (char **) argv_xvg,
			       NULL, NULL, 0);
  
  UxDisplay = XtDisplay(UxTopLevel);
  UxScreen = XDefaultScreen(UxDisplay);

  /* We set the geometry of UxTopLevel so that dialogShells
     that are parented on it will get centered on the screen
     (if defaultPosition is B_TRUE). */
  
  XtVaSetValues(UxTopLevel,
		XtNx, 0,
		XtNy, 0,
		XtNwidth, DisplayWidth(UxDisplay, UxScreen),
		XtNheight, DisplayHeight(UxDisplay, UxScreen),
		NULL);
}  

main( int argc, char **argv)
{
  /*-----------------------------------------------------------
   * Declarations.
   * The default identifier - mainIface will only be declared 
   * if the interface function is global and of type swidget.
   * To change the identifier to a different name, modify the
   * string mainIface in the file "xtmain.dat". If "mainIface"
   * is declared, it will be used below where the return value
   * of  PJ_INTERFACE_FUNCTION_CALL will be assigned to it.
   *----------------------------------------------------------*/ 
  
  swidget mainIface;
  
  /*---------------------------------
   * Interface function declaration
   *--------------------------------*/	
  
  swidget create_XvgShell(int argc, char **argv);
  
  /*---------------------
   * Initialize program
   *--------------------*/
  argc_xvg = argc;
  argv_xvg = argv;
  XvgInitVariables();
  XvgMM_Init();
  
  /* execute in non-interactive mode if required, and exit... */
  PeekNoInteractive(argc, argv);

  /*-------------------------------------------------------
   * fire up X-Windows
   *------------------------------------------------------*/
  XvgInitX();
#ifndef CMGUI
  InitHierarchy();
#endif
  
  
  /*----------------------------------------------------------------
   * Create and popup the first window of the interface.  The 	 
   * return value can be used in the popdown or destroy functions.
   * The Widget return value of  PJ_INTERFACE_FUNCTION_CALL will 
   * be assigned to "mainIface" from  PJ_INTERFACE_RETVAL_TYPE. 
   *---------------------------------------------------------------*/
  mainIface = create_XvgShell(argc_xvg, argv_xvg);

  /*-----------------------
   * Enter the event loop 
   *----------------------*/
  
  XtAppMainLoop (UxAppContext);
  
}
#else 
#include "user_interface/user_interface.h" 
#include "finite_element/finite_element.h" 

/*???DB.  Not needed ? */
struct GROUP(FE_node) *CurrentFENodeGroup;

/* global variables externally defined in xvg/include/XvgGlobals.h */
struct MANAGER(FE_field) *xvg_fe_field_manager=(struct MANAGER(FE_field) *)NULL;
struct MANAGER(FE_node) *xvg_node_manager=(struct MANAGER(FE_node) *)NULL;
struct MANAGER(GROUP(FE_node)) *xvg_node_group_manager=
	(struct MANAGER(GROUP(FE_node)) *)NULL;

void xvg_popup_interface(struct MANAGER(FE_field) *fe_field_manager,
	struct MANAGER(FE_node) *node_manager,
	struct MANAGER(GROUP(FE_node)) *node_group_manager,
	struct User_interface *user_interface) 
{
  if (XvgUp) 
    return; 
  XvgInitVariables();
  XvgUp = B_TRUE; 
  UxAppContext = user_interface->application_context; 
  UxTopLevel = user_interface->application_shell; 
  UxDisplay = user_interface->display; 
  UxScreen = DefaultScreen(user_interface->display); 
  XvgMM_Init();
	InitHierarchy();
	xvg_fe_field_manager=fe_field_manager;
	xvg_node_manager=node_manager;
	xvg_node_group_manager=node_group_manager;
  UxPopupInterface((swidget) create_XvgShell(0, NULL), no_grab); 
} 
#endif 


/***************************************************************************
NAME:		UxMrmFetchError(hierarchy_id, widget_name, parent_wgt, status)
INPUT:		MrmHierarchy	h_id		: Mrm hierarchy
		String		widget_name	: name of widget being fetched
		Widget		p_wgt		: parent widget
		Cardinal	stat		: MrmFetchWidget return value
OUTPUT:		---
RETURN:		void
DESCRIPTION:	This function is called from the generated C code
		if the call to MrmFetchWidget() fails.  It is provided
		so that you can control what happens in that case.

---------------------------------------------------------------------------*/
#ifdef _NO_PROTO
void	UxMrmFetchError(h_id, widget_name, p_wgt, stat)
	MrmHierarchy	h_id;
	String		widget_name;
	Widget		p_wgt;
	Cardinal	stat;
#else
void	UxMrmFetchError(MrmHierarchy	h_id,
			String		widget_name,
			Widget		p_wgt,
			Cardinal	stat)
#endif /* _NO_PROTO */
{
	MrmHierarchy	hierarchy_id = h_id;
	Widget		parent_wgt = p_wgt;
	Cardinal	status	= stat;

	fprintf(stderr, "MrmFetchWidget(%s) failed ... exiting\n", widget_name);

	exit(EXIT_FAILURE);
}

/***************************************************************************
NAME:		UxMrmOpenHierarchy(uid_file)
INPUT:		char	*uid_file		: name of UID file
OUTPUT:		---
RETURN:		MrmHierarchy			: Mrm hierarchy id
DESCRIPTION:	Opens the given UID file and returns the Mrm hierarchy id
		to be used in subsequent Mrm operations.
		You should have a call to this for each interface in your
		application and the returned id should be used to initialize
		a global variable named <interface_name>_MrmId.

		This function is made global so that you have the option
		of calling it in the initial code of an interface rather than
		from main().

---------------------------------------------------------------------------*/
#ifdef _NO_PROTO
MrmHierarchy	UxMrmOpenHierarchy(uid_file)
	char	*uid_file;
#else
MrmHierarchy	UxMrmOpenHierarchy( char *uid_file)
#endif /* _NO_PROTO */
{
	Cardinal	status;
	MrmHierarchy	hierarchy_id = NULL;

	status = MrmOpenHierarchy(1, &uid_file, NULL, &hierarchy_id);
	if (status == MrmFAILURE)
	{
		fprintf(stderr,
			"UxMrmOpenHierarchy(%s) failed\n",
					uid_file);
		exit(EXIT_FAILURE);
	}
	else if (status == MrmNOT_FOUND)
	{
		fprintf(stderr,
			"UxMrmOpenHierarchy(%s) failed: file not found\n",
					uid_file);
		exit(EXIT_FAILURE);
	}

	return (hierarchy_id);
}

/***************************************************************************
NAME:		UxMrmRegisterClass(fcn_name, fcn_ptr)
INPUT:		char	*fcn_name	: name of convenience function
		Widget	(*fcn_ptr)()	: convenience function pointer
OUTPUT:		---
RETURN:		void
DESCRIPTION:	Registers the given convenience function with Mrm
		so that the function name can be used with the
		'user_defined' feature in UIL code.

---------------------------------------------------------------------------*/
#ifdef _NO_PROTO
void	UxMrmRegisterClass(fcn_name, fcn_ptr)
	char	*fcn_name;
	Widget	(*fcn_ptr)();
#else
void	UxMrmRegisterClass( char *fcn_name, Widget (*fcn_ptr)())
#endif /* _NO_PROTO */
{
	MrmRegisterClass(MrmwcUnknown,
			"UserDefined",
			fcn_name,
			fcn_ptr,
			widgetClass);
}


/*-------------------------------------------------------------------------*/
