

#if !defined GENERATED_VERSION_H
#define GENERATED_VERSION_H

#define CMISS_NAME_STRING "CMISS(cmgui)"
#define CMISS_VERSION_STRING @CMISS_VERSION_STRING@
#define CMISS_COPYRIGHT_STRING "Copyright 1996-2012, Auckland UniServices Ltd."
#define CMISS_SVN_REVISION_STRING @CMISS_SVN_REVISION_STRING@
#define CMISS_BUILD_STRING @CMISS_BUILD_STRING@

#endif

