/*
 * @(#)mat.h    generated by: makeheader    Tue Jun 22 16:36:50 1993
 *
 *		built from:	/rel/bld/matlab4/sun4/ansi.joe/sandbox4/src/file/matintrf.c
 */

#ifndef mat_h
#define mat_h


#include <stdio.h>
#ifndef VERSION_H
#include "matrix.h"
#endif


#define matREAD		0
#define matWRITE	1
#define matAPPEND	2


typedef struct matfile MATFile;

typedef struct {
  long type;
  long mrows;
  long ncols;
  long imagf;
  long namlen;
} Fmatrix;

extern	MATFile *matOpen(char *filename, char *mode);
extern	int      matClose(MATFile *ph);
extern	FILE    *matGetFp(MATFile *ph);
extern	void     matFreeDir(char **dir, int nentries);
extern	char   **matGetDir(MATFile *ph, int *num);
extern	int      matDeleteMatrix(MATFile *ph, char *name);
extern	Matrix  *matGetMatrix(MATFile *ph, char *name);
extern	int      matPutMatrix(MATFile *ph, Matrix *mp);
extern	Matrix  *matGetNextMatrix(MATFile *ph);
extern	int      matGetFull(MATFile *ph, char *name, int *m, int *n,
			    double **pr, double **pi);
extern	int      matPutFull(MATFile *ph, char *name, int m, int n,
			    double *pr, double *pi);		
extern	int      matGetString(MATFile *ph, char *name, char *string,
			      int str_len);
extern	int      matPutString(MATFile *ph, char *name, char *string);

#endif /* mat_h */
